import {
  Activity,
  Anvil,
  Baby,
  BabyIcon,
  BadgeCheck,
  Banknote,
  Bed,
  Beef,
  Bike,
  Bird,
  Bone,
  Book,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Bus,
  Cable,
  Calculator,
  Calendar,
  Camera,
  Car,
  CarFront,
  Cat,
  ChefHat,
  Clock,
  Clock3,
  Code,
  Coffee,
  Construction,
  CookingPot,
  Cpu,
  Crown,
  Dog,
  DoorOpen,
  Drill,
  Droplet,
  Droplets,
  Dumbbell,
  Factory,
  FerrisWheel,
  FileCheck,
  FileText,
  Fish,
  FlaskConical,
  Flower2,
  Footprints,
  Forklift,
  Gamepad2,
  Gem,
  Glasses,
  GraduationCap,
  Hammer,
  Hand,
  HardHat,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Hotel,
  KeyRound,
  KeySquare,
  Keyboard,
  Lamp,
  Laptop,
  Layers,
  MapPin,
  Monitor,
  MoreHorizontal,
  Mountain,
  Music,
  Package,
  PaintRoller,
  Paintbrush,
  Palette,
  Palmtree,
  PartyPopper,
  PawPrint,
  Phone,
  Plane,
  Printer,
  Refrigerator,
  Ribbon,
  Scale,
  Scissors,
  Settings,
  Ship,
  Shirt,
  ShoppingBag,
  Smartphone,
  Sofa,
  Sparkles,
  Sprout,
  Stethoscope,
  Store,
  Tablet,
  Tent,
  TicketsPlane,
  ToyBrick,
  Tractor,
  TreePine,
  Trees,
  Trophy,
  Truck,
  Tv,
  User,
  UserSearch,
  Users,
  UtensilsCrossed,
  Wallet,
  WashingMachine,
  Watch,
  Wheat,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

import {
  CATCHALL_ICON_NAME,
  CATEGORY_ICON_NAMES,
  FALLBACK_ICON_NAME,
  type CategoryIconName,
} from "@/lib/category-icon-names";

/**
 * FIX-SCAN-1 ISSUE 4 — ONE GLYPH PER ALLOWLISTED NAME.
 *
 * `Record<CategoryIconName, LucideIcon>` is the totality gate: adding a name to
 * the allowlist without a glyph here is a TYPE ERROR, so the console, the rail
 * and the suggester can no longer disagree about what a stored icon renders as.
 */
export const CATEGORY_GLYPHS: Record<CategoryIconName, LucideIcon> = {
  Activity,
  Anvil,
  Baby,
  BabyIcon,
  BadgeCheck,
  Banknote,
  Bed,
  Beef,
  Bike,
  Bird,
  Bone,
  Book,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Bus,
  Cable,
  Calculator,
  Calendar,
  Camera,
  Car,
  CarFront,
  Cat,
  ChefHat,
  Clock,
  Clock3,
  Code,
  Coffee,
  Construction,
  CookingPot,
  Cpu,
  Crown,
  Dog,
  DoorOpen,
  Drill,
  Droplet,
  Droplets,
  Dumbbell,
  Factory,
  FerrisWheel,
  FileCheck,
  FileText,
  Fish,
  FlaskConical,
  Flower2,
  Footprints,
  Forklift,
  Gamepad2,
  Gem,
  Glasses,
  GraduationCap,
  Hammer,
  Hand,
  HardHat,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Hotel,
  KeyRound,
  KeySquare,
  Keyboard,
  Lamp,
  Laptop,
  Layers,
  MapPin,
  Monitor,
  MoreHorizontal,
  Mountain,
  Music,
  Package,
  PaintRoller,
  Paintbrush,
  Palette,
  Palmtree,
  PartyPopper,
  PawPrint,
  Phone,
  Plane,
  Printer,
  Refrigerator,
  Ribbon,
  Scale,
  Scissors,
  Settings,
  Ship,
  Shirt,
  ShoppingBag,
  Smartphone,
  Sofa,
  Sparkles,
  Sprout,
  Stethoscope,
  Store,
  Tablet,
  Tent,
  TicketsPlane,
  ToyBrick,
  Tractor,
  TreePine,
  Trees,
  Trophy,
  Truck,
  Tv,
  User,
  UserSearch,
  Users,
  UtensilsCrossed,
  Wallet,
  WashingMachine,
  Watch,
  Wheat,
  Wrench,
  Zap,
};

/** The glyph for a stored icon name; `Package` when the name is unknown. */
export function categoryGlyph(name: string | null | undefined): LucideIcon {
  if (!name) return Package;
  return CATEGORY_GLYPHS[name.trim() as CategoryIconName] ?? Package;
}

/**
 * UX-2 PART 1 — THE CATCH-ALL GLYPH IS FIXED (the name lives in the allowlist
 * module so tests and the server can read it without importing lucide).
 */
/** The glyph a roster row renders: the catch-all glyph wins over the stored name. */
export function categoryRowGlyph(
  name: string | null | undefined,
  isCatchall: boolean,
): { Glyph: LucideIcon; iconName: string } {
  if (isCatchall) {
    return { Glyph: CATEGORY_GLYPHS[CATCHALL_ICON_NAME], iconName: CATCHALL_ICON_NAME };
  }
  const resolved = isKnownCategoryIcon(name) ? name!.trim() : FALLBACK_ICON_NAME;
  return { Glyph: categoryGlyph(name), iconName: resolved };
}

/** True when the stored name resolves to a real glyph rather than the fallback. */
export function isKnownCategoryIcon(name: string | null | undefined): boolean {
  if (!name) return false;
  return (CATEGORY_ICON_NAMES as readonly string[]).includes(name.trim());
}

export { CATCHALL_ICON_NAME, FALLBACK_ICON_NAME };
