/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DevTallRouteImport } from './routes/dev.tall'
import { Route as DevPrimitivesRouteImport } from './routes/dev.primitives'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AuthResetRouteImport } from './routes/auth_.reset'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as ApiTranslateRouteImport } from './routes/api/translate'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTranslationsRouteImport } from './routes/admin.translations'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'
import { Route as AdminImagesRouteImport } from './routes/admin.images'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAttributesRouteImport } from './routes/admin.attributes'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users_.$userId'
import { Route as AdminTranslationsLangRouteImport } from './routes/admin.translations_.$lang'
import { Route as AdminRolesRoleIdRouteImport } from './routes/admin.roles_.$roleId'
import { Route as AdminImpersonationSessionIdRouteImport } from './routes/admin.impersonation_.$sessionId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DevTallRoute = DevTallRouteImport.update({
  id: '/dev/tall',
  path: '/dev/tall',
  getParentRoute: () => rootRouteImport,
} as any)
const DevPrimitivesRoute = DevPrimitivesRouteImport.update({
  id: '/dev/primitives',
  path: '/dev/primitives',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth_/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTranslationsRoute = AdminTranslationsRouteImport.update({
  id: '/translations',
  path: '/translations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImagesRoute = AdminImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttributesRoute = AdminAttributesRouteImport.update({
  id: '/attributes',
  path: '/attributes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users_/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTranslationsLangRoute = AdminTranslationsLangRouteImport.update({
  id: '/translations_/$lang',
  path: '/translations/$lang',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoleIdRoute = AdminRolesRoleIdRouteImport.update({
  id: '/roles_/$roleId',
  path: '/roles/$roleId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImpersonationSessionIdRoute =
  AdminImpersonationSessionIdRouteImport.update({
    id: '/impersonation_/$sessionId',
    path: '/impersonation/$sessionId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRoute
  '/admin/attributes': typeof AdminAttributesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/images': typeof AdminImagesRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/translate': typeof ApiTranslateRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset': typeof AuthResetRoute
  '/c/$slug': typeof CSlugRoute
  '/dev/primitives': typeof DevPrimitivesRoute
  '/dev/tall': typeof DevTallRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/impersonation/$sessionId': typeof AdminImpersonationSessionIdRoute
  '/admin/roles/$roleId': typeof AdminRolesRoleIdRoute
  '/admin/translations/$lang': typeof AdminTranslationsLangRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRoute
  '/admin/attributes': typeof AdminAttributesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/images': typeof AdminImagesRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/translate': typeof ApiTranslateRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset': typeof AuthResetRoute
  '/c/$slug': typeof CSlugRoute
  '/dev/primitives': typeof DevPrimitivesRoute
  '/dev/tall': typeof DevTallRoute
  '/admin': typeof AdminIndexRoute
  '/admin/impersonation/$sessionId': typeof AdminImpersonationSessionIdRoute
  '/admin/roles/$roleId': typeof AdminRolesRoleIdRoute
  '/admin/translations/$lang': typeof AdminTranslationsLangRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRoute
  '/admin/attributes': typeof AdminAttributesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/images': typeof AdminImagesRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/translate': typeof ApiTranslateRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/auth_/reset': typeof AuthResetRoute
  '/c/$slug': typeof CSlugRoute
  '/dev/primitives': typeof DevPrimitivesRoute
  '/dev/tall': typeof DevTallRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/impersonation_/$sessionId': typeof AdminImpersonationSessionIdRoute
  '/admin/roles_/$roleId': typeof AdminRolesRoleIdRoute
  '/admin/translations_/$lang': typeof AdminTranslationsLangRoute
  '/admin/users_/$userId': typeof AdminUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/settings'
    | '/admin/attributes'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/images'
    | '/admin/locations'
    | '/admin/roles'
    | '/admin/translations'
    | '/admin/users'
    | '/api/translate'
    | '/auth/callback'
    | '/auth/reset'
    | '/c/$slug'
    | '/dev/primitives'
    | '/dev/tall'
    | '/admin/'
    | '/admin/impersonation/$sessionId'
    | '/admin/roles/$roleId'
    | '/admin/translations/$lang'
    | '/admin/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/settings'
    | '/admin/attributes'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/images'
    | '/admin/locations'
    | '/admin/roles'
    | '/admin/translations'
    | '/admin/users'
    | '/api/translate'
    | '/auth/callback'
    | '/auth/reset'
    | '/c/$slug'
    | '/dev/primitives'
    | '/dev/tall'
    | '/admin'
    | '/admin/impersonation/$sessionId'
    | '/admin/roles/$roleId'
    | '/admin/translations/$lang'
    | '/admin/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/settings'
    | '/admin/attributes'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/images'
    | '/admin/locations'
    | '/admin/roles'
    | '/admin/translations'
    | '/admin/users'
    | '/api/translate'
    | '/auth_/callback'
    | '/auth_/reset'
    | '/c/$slug'
    | '/dev/primitives'
    | '/dev/tall'
    | '/admin/'
    | '/admin/impersonation_/$sessionId'
    | '/admin/roles_/$roleId'
    | '/admin/translations_/$lang'
    | '/admin/users_/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  SettingsRoute: typeof SettingsRoute
  ApiTranslateRoute: typeof ApiTranslateRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetRoute: typeof AuthResetRoute
  CSlugRoute: typeof CSlugRoute
  DevPrimitivesRoute: typeof DevPrimitivesRoute
  DevTallRoute: typeof DevTallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dev/tall': {
      id: '/dev/tall'
      path: '/dev/tall'
      fullPath: '/dev/tall'
      preLoaderRoute: typeof DevTallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/primitives': {
      id: '/dev/primitives'
      path: '/dev/primitives'
      fullPath: '/dev/primitives'
      preLoaderRoute: typeof DevPrimitivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/reset': {
      id: '/auth_/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/translations': {
      id: '/admin/translations'
      path: '/translations'
      fullPath: '/admin/translations'
      preLoaderRoute: typeof AdminTranslationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/images': {
      id: '/admin/images'
      path: '/images'
      fullPath: '/admin/images'
      preLoaderRoute: typeof AdminImagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attributes': {
      id: '/admin/attributes'
      path: '/attributes'
      fullPath: '/admin/attributes'
      preLoaderRoute: typeof AdminAttributesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users_/$userId': {
      id: '/admin/users_/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/translations_/$lang': {
      id: '/admin/translations_/$lang'
      path: '/translations/$lang'
      fullPath: '/admin/translations/$lang'
      preLoaderRoute: typeof AdminTranslationsLangRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles_/$roleId': {
      id: '/admin/roles_/$roleId'
      path: '/roles/$roleId'
      fullPath: '/admin/roles/$roleId'
      preLoaderRoute: typeof AdminRolesRoleIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/impersonation_/$sessionId': {
      id: '/admin/impersonation_/$sessionId'
      path: '/impersonation/$sessionId'
      fullPath: '/admin/impersonation/$sessionId'
      preLoaderRoute: typeof AdminImpersonationSessionIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAttributesRoute: typeof AdminAttributesRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminImagesRoute: typeof AdminImagesRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminTranslationsRoute: typeof AdminTranslationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminImpersonationSessionIdRoute: typeof AdminImpersonationSessionIdRoute
  AdminRolesRoleIdRoute: typeof AdminRolesRoleIdRoute
  AdminTranslationsLangRoute: typeof AdminTranslationsLangRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAttributesRoute: AdminAttributesRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminImagesRoute: AdminImagesRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminTranslationsRoute: AdminTranslationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminImpersonationSessionIdRoute: AdminImpersonationSessionIdRoute,
  AdminRolesRoleIdRoute: AdminRolesRoleIdRoute,
  AdminTranslationsLangRoute: AdminTranslationsLangRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  SettingsRoute: SettingsRoute,
  ApiTranslateRoute: ApiTranslateRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetRoute: AuthResetRoute,
  CSlugRoute: CSlugRoute,
  DevPrimitivesRoute: DevPrimitivesRoute,
  DevTallRoute: DevTallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
