-- U0i PART 1 — provisional Amharic category names.
-- PROVISIONAL — pre-native-review; U5 console + native review refine (launch-gate item)
-- Idempotent + additive: only fills name_am where it is still NULL; never overwrites.
UPDATE public.categories AS c
SET name_am = v.name_am, updated_at = now()
FROM (VALUES
  ('accessories','መለዋወጫዎች'),
  ('agriculture-farming','ግብርና እና እርሻ'),
  ('apartments-for-rent','ለኪራይ አፓርታማዎች'),
  ('apartments-for-sale','ለሽያጭ አፓርታማዎች'),
  ('audio-headphones','ኦዲዮ እና ጆሮ ማዳመጫዎች'),
  ('auto-parts','መለዋወጫዎች እና እቃዎች'),
  ('automotive','አውቶሞቲቭ'),
  ('babies-kids','ህጻናት እና ልጆች'),
  ('baby-clothing','የህጻናት ልብስ'),
  ('beauty-personal-care','ውበት እና የግል እንክብካቤ'),
  ('birds','ወፎች'),
  ('cameras-photography','ካሜራዎች እና ፎቶግራፍ'),
  ('cars','መኪናዎች'),
  ('cats','ድመቶች'),
  ('commercial-equipment','የንግድ መሳሪያዎች'),
  ('commercial-property','የንግድ ንብረት'),
  ('compact-sedans','ትናንሽ ሴዳኖች'),
  ('computer-accessories','የኮምፒውተር መለዋወጫዎች'),
  ('computer-components','አካላት እና መለዋወጫዎች'),
  ('computers','ኮምፒውተሮች'),
  ('construction-equipment','የግንባታ መሳሪያዎች'),
  ('coupes','ኩፔዎች'),
  ('creative-services','የፈጠራ አገልግሎቶች'),
  ('desktops','ዴስክቶፖች'),
  ('dogs','ውሾች'),
  ('education-training','ትምህርት እና ስልጠና'),
  ('electric-vehicles','የኤሌክትሪክ ተሽከርካሪዎች'),
  ('electronics','ኤሌክትሮኒክስ'),
  ('farm-equipment','የእርሻ መሳሪያዎች'),
  ('fashion','ፋሽን'),
  ('feature-phones','ተራ ስልኮች'),
  ('fertilizers-chemicals','ማዳበሪያ እና ኬሚካሎች'),
  ('fish-aquariums','ዓሳ እና አኳሪየም'),
  ('fitness-gym','ጂም እና የአካል ብቃት'),
  ('fragrances','ሽቶዎች'),
  ('freelance-contract','ፍሪላንስ እና ኮንትራት'),
  ('full-time-jobs','የሙሉ ጊዜ ስራዎች'),
  ('fullsize-sedans','ትላልቅ ሴዳኖች'),
  ('furniture','የቤት እቃዎች'),
  ('garden-outdoor','አትክልት እና የውጪ ቦታ'),
  ('hair-care','የፀጉር እንክብካቤ'),
  ('harvested-produce','የተሰበሰበ ምርት'),
  ('hatchbacks','ሃችባኮች'),
  ('home-decor','የቤት ማስዋቢያ'),
  ('home-garden','ቤት እና አትክልት'),
  ('home-services','የቤት አገልግሎቶች'),
  ('houses-for-rent','ለኪራይ ቤቶች'),
  ('houses-for-sale','ለሽያጭ ቤቶች'),
  ('internships','የልምምድ ስራዎች'),
  ('job-seekers-cvs','ስራ ፈላጊዎች እና ሲቪዎች'),
  ('jobs','ስራዎች'),
  ('kids-clothing','የልጆች ልብስ'),
  ('kitchen-dining','ኩሽና እና መመገቢያ'),
  ('land-plots','መሬት እና ቦታዎች'),
  ('laptops','ላፕቶፖች'),
  ('livestock','ከብቶች'),
  ('livestock-feed','የከብት መኖ'),
  ('luxury-cars','የቅንጦት መኪናዎች'),
  ('makeup','ሜካፕ'),
  ('medical-equipment','የህክምና መሳሪያዎች'),
  ('mens-clothing','የወንዶች ልብስ'),
  ('midsize-sedans','መካከለኛ ሴዳኖች'),
  ('motorcycles','ሞተር ሳይክሎች'),
  ('nursery-furniture','የህጻናት የቤት እቃዎች'),
  ('office-equipment','የቢሮ መሳሪያዎች'),
  ('other-computers','ሌሎች ኮምፒውተሮች'),
  ('outdoor-recreation','የውጪ መዝናኛ'),
  ('part-time-jobs','የትርፍ ጊዜ ስራዎች'),
  ('pet-services','የቤት እንስሳት አገልግሎቶች'),
  ('pet-supplies','የቤት እንስሳት እቃዎች'),
  ('pets-animals','የቤት እንስሳት'),
  ('phone-accessories','የስልክ መለዋወጫዎች'),
  ('phone-repair-services','የጥገና አገልግሎቶች'),
  ('phones-tablets','ስልኮች እና ታብሌቶች'),
  ('professional-services','የሙያ አገልግሎቶች'),
  ('real-estate','ሪል እስቴት'),
  ('restaurant-equipment','የምግብ ቤት መሳሪያዎች'),
  ('roommates-shared','የክፍል ጓደኛ እና የጋራ መኖሪያ'),
  ('sedans','ሴዳኖች'),
  ('seeds-plants','ዘሮች እና ተክሎች'),
  ('services','አገልግሎቶች'),
  ('shoes-footwear','ጫማዎች'),
  ('short-term-rentals','የአጭር ጊዜ ኪራይ'),
  ('skincare','የቆዳ እንክብካቤ'),
  ('smartphones','ስማርት ስልኮች'),
  ('software','ሶፍትዌር'),
  ('sports-equipment','የስፖርት መሳሪያዎች'),
  ('sports-leisure','ስፖርት እና መዝናኛ'),
  ('strollers-car-seats','የህጻናት ጋሪ እና የመኪና ወንበር'),
  ('suvs','ኤስዩቪዎች'),
  ('tablets','ታብሌቶች'),
  ('toys-games','መጫወቻዎች እና ጨዋታዎች'),
  ('trucks','የጭነት መኪናዎች'),
  ('vehicles','ተሽከርካሪዎች'),
  ('wellness-fitness','ጤና እና የአካል ብቃት'),
  ('womens-clothing','የሴቶች ልብስ'),
  ('work-from-home','ከቤት ሆኖ መስራት')
) AS v(slug, name_am)
WHERE c.slug = v.slug AND c.name_am IS NULL;