// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwmvxvzzvjvtdcfcwiuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3bXZ4dnp6dmp2dGRjZmN3aXVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUzMDY0NDcsImV4cCI6MjEwMDg4MjQ0N30.UqAshzyHlrDueahVNHDAdfWToeps1L-VthZ_qgDzfvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});